name: Generate Changelog

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag from main repo'
        required: true
      trigger_secret:
        description: 'Common Secret stored in both repos for Authentication'
        required: true

permissions:
      contents: write

jobs:
  process-release:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Trigger Source
        env:
          RECIEVED_SECRET: ${{ inputs.trigger_secret }}
          EXPECTED_SECRET: ${{ secrets.TRIGGER_SECRET }}
        run: |
          if [ "$RECIEVED_SECRET" != "$EXPECTED_SECRET" ]; then
            echo "Unauthorized trigger"
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: pip install -r requirements.txt
          
      - name: Run Script
        env:
          RELEASE_TAG: ${{ inputs.release_tag }}
          GITHUB_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: python scripts/create_changelog.py "$RELEASE_TAG"
      
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "changelog-generater[bot]"
          git config --global user.email "noreply@github-actions.com"
          git add .
          git commit -m "Added changelog for release: ${{ inputs.release_tag }}"
          git push
