name: Download Release Tag Artifact

on:
  workflow_run:
    workflows:
      - "Upload Release Data as Artifact"
    types:
      - completed

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: release_tag

      - name: Read Release Tag
        run: |
          cat release_tag.txt
