name: Receive Workflow from Repo A

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag from Repo A'
        required: true
      trigger_secret:
        description: 'Hashed verification secret'
        required: true

jobs:
  process-release:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Trigger Source
        env:
          RECIEVED_SECRET: ${{ inputs.trigger_secret }}
          EXPECTED_SECRET: ${{ secrets.EXPECTED_TRIGGER_SECRET }}
        run: |
          if [ "$RECIEVED_SECRET" != "$EXPECTED_SECRET" ]; then
            echo "Unauthorized trigger"
            exit 1
          fi

      - name: Use Release Tag
        run: echo "Processing release ${{ inputs.release_tag }}"