name: Receive Workflow from Repo A

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag from Repo A'
        required: true
      secret_hash:
        description: 'Hashed verification secret'
        required: true

jobs:
  process-release:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Trigger Source
        env:
          RECEIVED_HASH: ${{ inputs.secret_hash }}
          EXPECTED_SECRET: ${{ secrets.EXPECTED_TRIGGER_SECRET }}
        run: |
          CALCULATED_HASH=$(echo -n "$EXPECTED_SECRET" | sha256sum | awk '{print $1}')
          if [ "$RECEIVED_HASH" != "$CALCULATED_HASH" ]; then
            echo "Unauthorized trigger"
            exit 1
          fi

      - name: Use Release Tag
        run: echo "Processing release ${{ inputs.release_tag }}"