name: Receive Workflow from Repo A

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag from Repo A'
        required: true

jobs:
  process-release:
    runs-on: ubuntu-latest
    steps:
      - name: Use Release Tag
        run: echo "Processing release ${{ inputs.release_tag }}"